name: deploy
on:
  push:
    branches:
      - 'ci/**'
    tags:
      - v**
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build .env file
        run: |
          rm .env || true
          touch .env

          cat <<EOF > .env
          NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }}
          NUXT_PUBLIC_SITE_URL=https://unicornranch.io
          # NUXT_CTA_BACKEND_URL=https://cta.unicornranch.io
          NUXT_CTA_BACKEND_URL=https://unicornranch-cta-backend-stage-yosk3uqzdq-ey.a.run.app
          NUXT_SITE_NAME=unicornranch.io
          NUXT_SITE_INDEXABLE=false
          EOF
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: ${{ steps.detect-package-manager.outputs.manager }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            dist
            .nuxt
          key: ${{ runner.os }}-nuxt-build-${{ hashFiles('dist') }}
          restore-keys: |
            ${{ runner.os }}-nuxt-build-
      - name: Install dependencies
        run: npm ci
      - name: Static HTML export with Nuxt
        run: npm run generate
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
